name: GitHub Actions Dependency

on:
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types: 
    - completed

jobs:
  GitHub-Actions-Dependency:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ran the dependency!"
      