name: build boards

on:
  workflow_dispatch:
env:
  ARTIFACT_DIR: $ARTIFACT_OUTPUT_DIR/a/$GITHUB_JOB/$GITHUB_RUN_NUMBER

jobs:
  things:
    runs-on: ubuntu-latest
    steps:
      - name: show things
        run: >
          echo "ARTIFACT_DIR: $ARTIFACT_DIR" &&
          echo "ARTIFACT_OUTPUT_DIR: $ARTIFACT_OUTPUT_DIR" &&
          echo "GITHUB_JOB: $GITHUB_JOB" &&
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
      - name: create artifact output directory - try a
        run: mkdir -p $ARTIFACT_DIR
      - name: create artifact output directory - try b
        run: mkdir -p $ARTIFACT_OUTPUT_DIR/a/$GITHUB_JOB/$GITHUB_RUN_NUMBER
      - name: eval
        run: tree
