name: build boards

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      artifact_dir: ${{ steps.create_path.outputs.artifact_dir }}
    steps:
      - name: create_path
        run: echo "artifact_dir=${{ vars.ARTIFACT_OUTPUT_DIR }}/$GITHUB_REPOSITORY_OWNER/$GITHUB_WORKFLOW/$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"

  things:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: show things again
        env:
            ARTIFACT_DIR: ${{ needs.prepare.outputs.artifact_dir }}
        run: >
          echo "vars.ARTIFACT_OUTPUT_DIR: ${{ vars.ARTIFACT_OUTPUT_DIR }}" &&
          echo "env.ARTIFACT_DIR: ${{ env.ARTIFACT_DIR }}" &&
          echo "ARTIFACT_DIR: $ARTIFACT_DIR" &&
          echo "GITHUB_JOB: $GITHUB_JOB" &&
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
      - name: create artifact output directory
        env:
            ARTIFACT_DIR: ${{ needs.prepare.outputs.artifact_dir }}
        run: mkdir -p $ARTIFACT_DIR
      - name: eval
        env:
            ARTIFACT_DIR: ${{ needs.prepare.outputs.artifact_dir }}
        run: tree $ARTIFACT_DIR
