name: build boards

on:
  workflow_dispatch:
env:
  ARTIFACT_DIR: $ARTIFACT_OUTPUT_DIR/a/$GITHUB_JOB/$GITHUB_RUN_NUMBER

jobs:
  things:
    runs-on: ubuntu-latest
    steps:
      - name: show things
        run: >
          echo "ARTIFACT_DIR: $ARTIFACT_DIR" &&
          echo "vars.ARTIFACT_OUTPUT_DIR: ${{ vars.ARTIFACT_OUTPUT_DIR }}" &&
          echo "ARTIFACT_OUTPUT_DIR: $ARTIFACT_OUTPUT_DIR" &&
          echo "GITHUB_JOB: $GITHUB_JOB" &&
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
      - name: create full path
        run: echo "ARTIFACT_DIR=${{ vars.ARTIFACT_OUTPUT_DIR }}/$GITHUB_JOB/$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: show things again
        run: >
          echo "ARTIFACT_DIR: $ARTIFACT_DIR" &&
          echo "vars.ARTIFACT_OUTPUT_DIR: ${{ vars.ARTIFACT_OUTPUT_DIR }}" &&
          echo "env.ARTIFACT_DIR: ${{ env.ARTIFACT_DIR }}" &&
          echo "ARTIFACT_OUTPUT_DIR: $ARTIFACT_OUTPUT_DIR" &&
          echo "GITHUB_JOB: $GITHUB_JOB" &&
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
      - name: create artifact output directory
        run: mkdir -p ${{ env.ARTIFACT_DIR }}
      - name: eval
        run: tree ${{ vars.ARTIFACT_OUTPUT_DIR }}
