name: GitHub Actions Demo

on:
  workflow_dispatch:

env:
  FOO: foo
  BAR: bar
  FOOBAR: $FOO$BAR

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "FOO is ${{ env.FOO }}, BAR is ${{ env.BAR }}, FOOBAR is ${{ env.FOOBAR }}."