name: GitHub Actions Demo
on: [push]

env:
  FOO: foo
  BAR: bar
  FOOBAR: ${{ env.FOO }}${{ env.BAR }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "FOO is ${{ env.FOO }}, BAR is ${{ env.BAR }}, FOOBAR is ${{ env.FOOBAR }}."
